theme:
  name: material
  language: ru
  palette:
    # Темная тема с серыми акцентами
    - scheme: slate
      primary: grey
      accent: blue
  features:
    - navigation.sections  # Группировка меню в блоки
    - navigation.expand    # Меню сразу раскрыто
    - navigation.top       # Кнопка "Вверх"
    - content.code.copy    # Кнопка "Копировать" для кода
