site_name: ViewGA Docs
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo

nav:
  - Главная: index.md
  - Создание карты:
      - Что такое карта?: map/index.md
      - Инициализация: map/initialization.md
