site_name: ViewGA Documentation
language: ru

theme:
  name: material
  palette:
    - scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Темная тема
    - scheme: default
      primary: grey
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Светлая тема
  
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy

nav:
  - Главная: index.md
  - Создание карты:
      - Что такое карта?: map/index.md
      - Инициализация: map/initialization.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
